#!/usr/bin/env python3
"""Build static demo data for the Birdeye Risk Radar web UI."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


DEFAULT_INPUT = Path("birdeye-radar.jsonl")
DEFAULT_OUTPUT = Path("radar-data.js")


def load_records(path: Path) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    summary: dict[str, Any] | None = None
    assessments: list[dict[str, Any]] = []

    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError as exc:
            raise ValueError(f"{path}:{line_number}: invalid JSONL record") from exc

        record_type = record.get("type")
        if record_type == "run_summary":
            summary = record
        elif record_type == "token_assessment":
            assessments.append(record)

    if summary is None:
        raise ValueError(f"{path}: missing run_summary record")
    if not assessments:
        raise ValueError(f"{path}: missing token_assessment records")
    return summary, assessments


def render_javascript(summary: dict[str, Any], assessments: list[dict[str, Any]]) -> str:
    payload = {
        "summary": summary,
        "assessments": assessments,
    }
    encoded = json.dumps(payload, indent=2, sort_keys=True)
    return (
        "/* Generated by tools/build_demo_data.py. Do not edit by hand. */\n"
        f"window.RADAR_DEMO_DATA = {encoded};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    args = parser.parse_args()

    summary, assessments = load_records(args.input)
    rendered = render_javascript(summary, assessments)

    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            raise SystemExit(f"{args.output} is stale; run tools/build_demo_data.py")
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output} with {len(assessments)} assessments")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
